[general]

# 下载alacritty-theme
import = ["alacritty-theme/themes/tokyo_night.toml"]
working_directory = "None"

[window]

decorations = "None"
startup_mode = "Maximized"

[font]

normal = { family = "Hack Nerd Font", style = "Regular" }
size = 16

[terminal.shell]

# 默认开启的终端
# program = "pwsh"
# args = ["-wd ~"]

[keyboard]

bindings = [
	{ key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
	{ key = "D", mods = "Control|Shift", command = { program = "alacritty", args = ["--command", "wsl -d Debian --cd ~"] }},
]
