[general]

# https://github.com/alacritty/alacritty-theme.git
import = ["alacritty-theme/themes/tokyo_night.toml"]
working_directory = "None"

[window]

decorations = "None"
startup_mode = "Maximized"

[font]

normal = { family = "Hack Nerd Font", style = "Regular" }
size = 16

[colors]

primary = { foreground = "#d8d8d8", background = "#181818" }
cursor = { text = "#181818", cursor = "#d8d8d8" }
vi_mode_cursor = { text = "#181818", cursor = "#d8d8d8" }

[terminal.shell]

# Windows下开启WSL
# program = "wsl.exe"
# args = ["-d Debian", "--cd ~"]

[keyboard]

bindings = [
	{ key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
]
